### PR TITLE
adding two code demos

### PR DESCRIPTION
**Pull request by Dawolee**
I followed the instructions, but didn't know which cloud hosted player to use (I just copied one from an existing demo) and whether or not to include my own Github credentials. Please let me know if I need to change anything!

Here are the two code demos live in my own S3 bucket:

https://s3.amazonaws.com/daniel.success.jwplayer.com/ab_replay.html
https://s3.amazonaws.com/daniel.success.jwplayer.com/JW_LiveChannels_check.html

### CODE REVIEW

**Comment by SageBrushes** [comment]
@monibons can we accept his incredible contributions?

**Comment by monibons** [comment]
Is this a forked branch? If so, can you please branch from within this project? It makes it easier to PR review and deploy feature branches to test on a staging environment.

Also, I can probably release the A-B Replay demo but not the Live Channels demo. We have a plugin for the player that is currently in development and being released in the next couple of weeks so we don't want to be sharing a different implementation than the recommended and supported one.

@SageBrushes FYI.

**Comment by monibons** [comment]
Also, in the future if you can also keep each demo on their separate branches it will also make it easier to release demos independently.

**Comment by Dawolee** [comment]
creating a new pull request after cloning the repo instead of forking

**Pull request closed without merging**
