### PR TITLE
Live channels demos improvements

### PR DESCRIPTION
**Pull request by jochem261**

### CODE REVIEW

**Review by RikHeijdens — APPROVED** [review]
LGTM

**Comment by jochem261** [comment]
@monibons , can this be merged. I am not authorized to merge.

**Comment by monibons** [comment]
@jochem261 I deployed to staging, can you review? If all looks good I can deploy to production.
http://staging-web-player-demos.longtailvideo.com/developers/web-player-demos/

**Comment by jochem261** [comment]
Just checked. Looks good to me! @monibons

**Pull request merged**
