### PR TITLE
SERV-11557: Update Player ID to a Player with the same qualities

### PR DESCRIPTION
**Pull request by dannyjgibson**
I've created a new player with the same properties as `lqsWlr4Z`, and I want to replace the old player on the demos page with this new player.

### CODE REVIEW

**Review by Dawolee — APPROVED** [review]
LGTM!

**Comment by monibons** [comment]
Thanks @dannyjgibson !

**Comment by dannyjgibson** [comment]
@monibons Thanks for doing that! Please keep us updated. Just as a heads up I do have permissions to merge this PR (even without approvals), not sure if we want to change my permissions at all or look into that. That's separate from our current issue, of course :)

**Comment by masterpro** [comment]
пн, 15 авг. 2022 г. в 21:20, Danny Gibson ***@***.***>:

**Comment by masterpro** [comment]
пн, 15 авг. 2022 г. в 21:17, Monica Parra ***@***.***>:

**Comment by masterpro** [comment]
пн, 15 авг. 2022 г. в 21:17, Monica Parra ***@***.***>:

**Comment by masterpro** [comment]
пн, 15 авг. 2022 г. в 21:15, Dawolee ***@***.***>:

**Comment by masterpro** [comment]
пн, 15 авг. 2022 г. в 21:12, Danny Gibson ***@***.***>:

**Pull request merged**
